version: "3"
services:
  db:
    image: "postgres:12"
    container_name: "wallet_postgres"
    ports:
      - "54320:5432"
    volumes:
      - wallet_dbdata:/var/lib/postgresql/data
volumes:
  wallet_dbdata:
